name: Issues Events
run-name: ${{ github.actor }} opened an issue

on:
  issues:
    types:
      - opened
      - edited

jobs:
  issue_events:
    runs-on: ubuntu-latest
    steps:
      - name: Triggered the workflow
        run: echo "${{ toJson(github.event) }}"